-- Generated by import_tutor.py from the WordPress export. Run after lms.sql.
-- Skips any course whose slug already exists, so your edits are never overwritten.

-- AI Skills for Kids  (Tutor course 4425, publish)
do $$
declare cid uuid;
begin
  if exists (select 1 from public.lms_courses where slug = 'ai-skills-for-kids') then return; end if;
  insert into public.lms_courses (slug, title, summary, description, age_range, cover_url, price_kes, is_published, position)
  values ('ai-skills-for-kids', $tw$AI Skills for Kids$tw$, $tw$Children are growing up surrounded by artificial intelligence, from phones and social media to school tools and games. Yet most children are never taught how AI works, how it…$tw$, $tw$Children are growing up surrounded by artificial intelligence, from phones and social media to school tools and games.
Yet most children are never taught **how AI works, how it learns, or how to use it responsibly**.

**AI Skills for Kids** fills this gap by helping learners understand AI clearly, think critically about technology, and develop strong ethical foundations - without requiring coding, expensive devices, or constant internet access.

#### **Grades 1–3 (Ages 7–9)**

#### **Learning Goal**

Understand **what AI is**, how it helps people, and how humans stay in control.

#### **Core Skills**

- Pattern recognition
- Following instructions (algorithms)
- Asking good questions
- Kind & ethical use of technology

#### **Key Topics**

- What is a machine?
- What is intelligence?
- Humans vs machines
- Step-by-step thinking

#### **Ages 7–9: AI Awareness**

Learners explore:

- What machines can and cannot do
- Patterns and instructions
- Kind and helpful technology

**Outcome:** Curiosity, confidence, ethical awareness$tw$,
          $tw$7–9$tw$, $tw$https://tinkerwith.me/wp-content/uploads/2026/01/Generated-Image-January-08-2026-6_56PM.png$tw$, 0, true, 1)
  returning id into cid;
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 1, $tw$📘 Lesson 1: Teach the Robot 🤖$tw$, $tw$Teach the Robot$tw$, $tw$**🧠 Key Idea**
A robot does not think like a human. It follows the steps.

**🧪 Activity**
Imagine your friend is a robot.
Give step-by-step instructions to:
Wash hands
Brush teeth
Pack a school bag

**✍🏽 Reflection**
What happened when instructions were unclear?
💡 Remember
AI only does what humans tell it to do.$tw$);
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 2, $tw$📘 Lesson 1: Teach the Robot 🤖$tw$, $tw$Advanced Activity: “Visual Coding Robot”$tw$, $tw$**Tools (Choose one):**

- Scratch Jr
- Scratch (simple blocks)
- Blockly-based tools

#### **🖥️ Setup (Before Class – 5 Minutes)**

1. Open the tool on all devices
2. Create a **new blank project**
3. Choose **one simple character (sprite)ActivityStep 1: Meet the Robot**

“This character is a robot.
It will only do **exactly** what we tell it.”

#### **Step 2: Give One Instruction**

drag **one movement block**:

- Move forward
- Turn left
- Turn right

Click **Play**.

**Learning:**

- What did the robot do?
- Did it do anything else?

**Step 3: Create a Sequence**

drag **3–5 blocks** in a row:

1. Move forward
2. Turn right
3. Move forward

Click **Play**.

**Learning:**

- Did the robot follow the order?
- What happens if we change the order?

**Step 4: Break It on Purpose**

- Remove one block
- Change the order
- Add an extra turn

Click **Play** again.

**Learning:**

- What went wrong?
- Did the robot fix the mistake?

🧠 **Key insight:**The robot doesn’t know what we *meant* — only what we *told* it.

**Step 5: Complete a Simple Task**

“Move the robot to the star.”

Tasks:

- Plan steps before dragging blocks
- Test
- Fix mistakes

**🧠 Reflection**

- Why did the robot get confused?
- What helped it succeed?
- Who is responsible when it fails?$tw$);
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 3, $tw$📘 Lesson 2: Spot the Pattern 🔁$tw$, $tw$Spot the Pattern$tw$, $tw$**🧠 Key Idea**Patterns help computers guess what comes next.

**🧪 Activity**Look at this pattern:

🍎 🍌 🍎 🍌 🍎 \_\_\_

What comes next?

Draw your own pattern.

**💡 Remember**Patterns help AI learn.$tw$);
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 4, $tw$📘 Lesson 2: Spot the Pattern 🔁$tw$, $tw$Advanced Activity: “Pattern Game Creator”$tw$, $tw$**Tools:**

- Scratch (simple blocks)
- Codingame (kids mode)

**Activity**

### **Steps**

1. Open Scratch → New project
2. Choose shapes or sprites
3. Create a repeating pattern (e.g. red–blue–red–blue)
4. Pause the pattern
5. Ask: *“What comes next?”*
6. Reveal the answer

**Reflection**

- How did the computer know what to repeat?
- What happens if the pattern changes?$tw$);
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 5, $tw$📘 Lesson 3: Kind or Unkind Technology ❤️$tw$, $tw$Kind or Unkind Technology ❤️$tw$, $tw$**🧠 Key Idea**Humans decide how technology is used.

**🧪 Activity**Is this kind or unkind?

- A robot helps clean a classroom
- A robot insults people

Discuss with your teacher or parent.

**💡 Remember**Kind technology helps people.$tw$);
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 6, $tw$📘 Lesson 3: Kind or Unkind Technology ❤️$tw$, $tw$Advanced Activity: Kind vs Unkind Tech Simulation ❤️$tw$, $tw$**Tools:**

- Interactive slides
- Simple branching story tools

### **Tools**

- Google Slides / PowerPoint

**Activity**

#### **Steps**

1. Slide 1: Problem scenario
2. Slide 2: Kind choice
3. Slide 3: Unkind choice
4. Link buttons to outcomes
5. Test choices

### **Reflection:**

- Who decided what happened?
- Was the computer kind by itself?

### **Learning**

✔ Ethics
✔ Cause & effect
✔ Human responsibility$tw$);
end $$;

-- What is Artificial Intelligence?  (Tutor course 4293, publish)
do $$
declare cid uuid;
begin
  if exists (select 1 from public.lms_courses where slug = 'what-is-ai') then return; end if;
  insert into public.lms_courses (slug, title, summary, description, age_range, cover_url, price_kes, is_published, position)
  values ('what-is-ai', $tw$What is Artificial Intelligence?$tw$, $tw$Category: Introductory AI & Ethics Duration: 30- 45 minutes Level: Beginner Audience: Parents, kids (10+), teachers$tw$, $tw$- Category: **Introductory AI & Ethics**
- Duration: 30- 45 minutes
- Level: Beginner
- Audience: Parents, kids (10+), teachers$tw$,
          $tw$10+$tw$, $tw$https://tinkerwith.me/wp-content/uploads/2025/09/make-an-image-for-a-course-asking-is-this-ai_.jpg$tw$, 1999, true, 2)
  returning id into cid;
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 1, $tw$What is Artificial Intelligence?$tw$, $tw$Lesson 1: AI in Everyday Life$tw$, $tw$**Overview**AI is not just science fiction; it’s part of your daily life! In this lesson, you’ll discover how artificial intelligence appears in tools you already use.

**Examples:**

- Voice assistants (e.g., Siri, Alexa, Google Assistant)
- Video or music recommendations (YouTube, Netflix, Spotify)
- Simple games or filters on phones

**Activity (Optional):**Watch this short explainer video:
[*(Link here)*](https://www.youtube.com/watch?v=uXbi3JqZiGA)

**Reflection Prompt:**Can you think of 3 more places where AI shows up in your life? Could you write them down?

**Assignment (optional):** Submit a short paragraph: *“Where I see AI every day”*.$tw$);
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 2, $tw$What is Artificial Intelligence?$tw$, $tw$Lesson 2 - Spotting AI: Activity$tw$, $tw$**Overview**Now that you’ve seen how AI shows up in everyday life, let’s test your detective skills!

**Activity:**Look at these scenarios and decide: *“AI or Not AI?”*

1. A calculator solves 25 × 12.
2. Netflix recommends the next movie.
3. A friend reminds you of homework.
4. Google Maps suggests the fastest route.

**Challenge:** Take the quiz in the section

Or try this game <https://sightengine.com/ai-or-not?version=2024Q3>

**Reflection Prompt:**Which example surprised you most? Why?

**Lesson type:** Quiz/Assignment
**Assignment idea:**Research other examples$tw$);
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 3, $tw$What is Artificial Intelligence?$tw$, $tw$Lesson 3 - How Simple Chatbots Work$tw$, $tw$**Overview**Chatbots seem smart, but most are built from simple rules: *“If the user says this, then reply with that.”*

**Mini-Activity:**Try out a **block-based chatbot builder, such as** Scratch or MIT App Inventor.

- [How to build a chatbot with Scratch](https://www.youtube.com/watch?v=wP_OsxPbdXA)

**Example Flow:**

- If someone types “Hi”, the bot says “Hello!”
- If someone asks, “What’s your name?”, the bot says, “I’m RoboHelper.”

**Reflection:**Imagine you’re designing a chatbot for your school. What would it help students with?

**Lesson type:** Practical / External link
**Assignment:** Describe one chatbot idea in a short paragraph.$tw$);
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 4, $tw$What is Artificial Intelligence?$tw$, $tw$Lesson 4- Ethics: A Short Story & Reflection$tw$, $tw$**Overview**AI is powerful, but it raises big questions. Let’s think about *ethics*.

**Short Story:**A robot guard dog sees two kids: one sneaking into school without a uniform, and another who has fallen and needs help.
The robot must choose: chase the uniform violator OR help the injured child.

**Discussion Questions:**

- What should the robot do first?
- Is that choice fair to everyone? Why or why not?

**Reflection Prompt:**Write 3–4 sentences sharing what you think is the “most fair” choice.

**Lesson type:** Text + Reflection
**Assignment idea:** Students submit their reflections in writing or audio.$tw$);
end $$;

-- AI Beginners Workbook  (Tutor course 4625, draft)
do $$
declare cid uuid;
begin
  if exists (select 1 from public.lms_courses where slug = 'ai-beginners-workbook') then return; end if;
  insert into public.lms_courses (slug, title, summary, description, age_range, cover_url, price_kes, is_published, position)
  values ('ai-beginners-workbook', $tw$AI Beginners Workbook$tw$, $tw$Hello and welcome to your very own AI Workbook This book will help you learn about Artificial Intelligence (AI) - the technology that lets machines think and act in ways that…$tw$, $tw$Hello and welcome to your very own AI Workbook! This book will help you learn about **Artificial Intelligence (AI) -** the technology that lets machines think and act in ways that seem smart.

We’ll explore:

- What AI is and why it’s important in Africa.
- Creative ways to use AI for art and music.
- How AI can help you with research and coding.
- How to stay safe and ethical when using AI tools.$tw$,
          $tw$9–13$tw$, $tw$https://tinkerwith.me/wp-content/uploads/2026/03/ai-images.jpg$tw$, 1999, false, 3)
  returning id into cid;
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 1, $tw$Chapter 1: What Is AI? (Simple Definition)$tw$, $tw$Why Should Kids Learn About AI?$tw$, $tw$- AI is being used in banks, phones, hospitals, and even on farms to help produce more food.
- Understanding AI can open up many exciting career opportunities.
- You can use AI to create solutions for your community.$tw$);
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 2, $tw$Chapter 1: What Is AI? (Simple Definition)$tw$, $tw$Chapter 1: What Is Artificial Intelligence?$tw$, $tw$**Definition and Key Concepts**

- **Data**: Information that we feed into AI systems.
- **Algorithm**: A set of rules or steps a computer follows to solve a problem.
- **Machine Learning**: The part of AI where computers “learn” from data.

**Real-Life Examples of AI Around Us**

- **Chatbots**: Answering customer questions online.
- **Recommendation Systems**: Suggesting videos or music to you (like on YouTube or Spotify).
- **Virtual Assistants**: Google Assistant, Siri, etc.
- **Fun Facts About AI**

  - Many languages in Africa are being preserved using AI translations.
  - Drones powered by AI can help deliver medicine to remote villages.$tw$);
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 3, $tw$Chapter 2: Careers in AI$tw$, $tw$AI Careers: Jobs of the Future$tw$, $tw$### Core AI Careers

| Career | What They Do | Example Work |
| --- | --- | --- |
| **AI Engineer** | Build intelligent systems that allow computers to learn and make decisions. | Chatbots, recommendation systems, smart assistants |
| **Machine Learning Engineer** | Design algorithms that help computers learn from data automatically. | Image recognition, fraud detection |
| **Data Scientist** | Study large sets of data to discover patterns and insights. | Predict trends, analyze customer behavior |
| **AI Research Scientist** | Explore new ideas and technologies that improve artificial intelligence. | Develop new AI models and algorithms |
| **Robotics Engineer** | Design and program robots that perform tasks automatically. | Factory robots, delivery robots |
| **Computer Vision Engineer** | Build systems that allow computers to understand images and videos. | Self-driving cars, facial recognition |
| **Natural Language Processing (NLP) Engineer** | Create systems that help computers understand human language. | Chatbots, translation tools |
| **AI Product Manager** | Lead teams that design and build AI-powered products. | Planning features for AI apps |
| **Automation Engineer** | Develop systems that automate tasks normally done by humans. | Warehouse robots, automated factories |

## Responsible AI Careers

| Career | What They Do | Example Work |
| --- | --- | --- |
| **AI Ethicist** | Ensure AI systems are fair, safe, and used responsibly. | Prevent bias in algorithms |
| **AI Policy Specialist** | Help governments create rules and laws for safe AI use. | AI regulations and governance |
| **AI Safety Researcher** | Study how to make advanced AI systems safe and reliable. | Risk analysis for AI systems |
| **Privacy Engineer** | Protect people's data when AI systems collect information. | Data protection systems |

## Creative AI Careers

| Career | What They Do | Example Work |
| --- | --- | --- |
| **AI Game Developer** | Use AI to make games more interactive and challenging. | Smart game characters |
| **AI Artist** | Use AI tools to create digital art, music, and animations. | AI-generated artwork |
| **AI Content Creator** | Create videos, graphics, and stories using AI tools. | Educational content, media production |
| **AI Interaction Designer** | Design how humans interact with AI systems. | Voice assistants, chatbot interfaces |

## AI in Science and Medicine

| Career | What They Do | Example Work |
| --- | --- | --- |
| **Health Technology Specialist** | Use AI to support doctors and healthcare systems. | Disease diagnosis tools |
| **Bioinformatics Scientist** | Use AI to analyze biological and genetic data. | DNA research |
| **Medical Imaging Specialist** | Use AI to analyze medical scans and images. | Detect tumours in X-rays |

## AI in Agriculture and Environment

| Career | What They Do | Example Work |
| --- | --- | --- |
| **Agricultural Technologist** | Use AI to improve farming and crop production. | Smart irrigation systems |
| **Precision Agriculture Specialist** | Use drones and AI sensors to monitor crops. | Crop health monitoring |
| **Environmental Data Scientist** | Use AI to study climate and environmental data. | Predict weather patterns |

## AI in Business and Industry

| Career | What They Do | Example Work |
| --- | --- | --- |
| **AI Consultant** | Help companies use AI to solve business problems. | AI adoption strategies |
| **AI Trainer** | Train AI systems by labelling and organizing data. | Training chatbots |
| **Business Intelligence Analyst** | Use data and AI to help businesses make decisions. | Market analysis |

## Emerging AI Careers

| Career | What They Do | Example Work |
| --- | --- | --- |
| **Prompt Engineer** | Write instructions that help AI generate useful results. | AI-generated content |
| **AI Education Specialist** | Teach people how to use AI technologies. | AI training programs |
| **AI Robotics Technician** | Maintain and repair AI-powered robots. | Robot maintenance |
| **Human-AI Collaboration Designer** | Design systems where humans and AI work together. | AI copilots |$tw$);
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 4, $tw$Chapter 3: AI for Creativity$tw$, $tw$Lesson Overview$tw$, $tw$Generative AI can create images, music, stories, and more. In this lesson, students will explore how AI tools can generate artwork from text descriptions.

Using tools like **DALL·E** and **Craiyon**, learners will write simple prompts and generate unique AI artwork.

By the end of this lesson, learners will be able to:

1. Explain what **Generative AI** is.
2. Use a **text prompt** to generate an image.
3. Create digital art using AI tools.
4. Improve prompts to produce better images.$tw$);
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 5, $tw$Chapter 3: AI for Creativity$tw$, $tw$What is Generative AI?$tw$, $tw$Generative AI is a type of artificial intelligence that can **create new content** such as images, music, text, or videos.

Instead of only analysing data, generative AI **produces something new** based on instructions given by a user.

Example:

If you type:

> "A robot painting a sunset over a futuristic city."

The AI will create an image based on that description.

## AI Tools for Creating Art

Two popular tools that generate images from text include:

- **DALL·E**
- **Craiyon**

These tools allow users to type a **description (prompt)** and generate artwork instantly.

# Activity: Create Your Own AI Artwork

## Instructions

1. Open one of the AI image generators.
2. Write a **creative description (prompt)** of an image you want.
3. Click **Generate**.
4. Review the images created by the AI.
5. Choose your **favorite image**.

## Example Prompts

Try prompts like:

- A robot painting a picture in an art studio
- A futuristic Nairobi city with flying cars
- A lion wearing sunglasses in pop art style
- An underwater classroom with students and a teacher

You can also add **art styles**, such as:

- cartoon style
- watercolor painting
- digital art
- realistic photography$tw$);
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 6, $tw$Chapter 3: AI for Creativity$tw$, $tw$Activity: Create Your Own AI Artwork$tw$, $tw$## Instructions

1. Open one of the AI image generators.
2. Write a **creative description (prompt)** of an image you want.
3. Click **Generate**.
4. Review the images created by the AI.
5. Choose your **favourite image**.

## Example Prompts

Try prompts like:

- A robot painting a picture in an art studio
- A futuristic Nairobi city with flying cars
- A lion wearing sunglasses in pop art style
- An underwater classroom with students and a teacher

You can also add **art styles**, such as:

- cartoon style
- watercolor painting
- digital art
- realistic photography$tw$);
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 7, $tw$Chapter 3: AI for Creativity$tw$, $tw$Assignment$tw$, $tw$Submit the following:

1. Your **AI-generated image**.
2. The **prompt you used** to create the image.
3. One sentence explaining what you like about the image.$tw$);
end $$;

-- Robotics 101  (Tutor course 4649, draft)
do $$
declare cid uuid;
begin
  if exists (select 1 from public.lms_courses where slug = 'robotics-101') then return; end if;
  insert into public.lms_courses (slug, title, summary, description, age_range, cover_url, price_kes, is_published, position)
  values ('robotics-101', $tw$Robotics 101$tw$, $tw$The course aims to introduce young learners to foundational concepts in robotics and coding through engaging hands-on activities and problem-solving projects. By fostering…$tw$, $tw$The course aims to introduce young learners to foundational concepts in robotics and coding through engaging hands-on activities and problem-solving projects. By fostering creativity, critical thinking, and collaboration, this curriculum makes complex topics accessible and enjoyable for children.

Through hands-on projects, students will develop valuable skills in technology, electronic circuit assembly for robotics, basic coding, and critical thinking. These foundational skills will prepare them for future opportunities in STEM fields and instil a sense of curiosity and innovation that will serve them throughout their educational journeys$tw$,
          '', $tw$https://tinkerwith.me/wp-content/uploads/2026/04/Tinkerwith-Traffic-Lights-scaled.png$tw$, 1999, false, 4)
  returning id into cid;
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 1, $tw$Assemble components$tw$, $tw$Use this components$tw$, $tw$Components needed:

- 1 Breadboard
- 1 Arduino
- 12 LEDs (3Green, 3 red and 3 Yellow
- 25 Jumper wires (13GND and 12 Signal)
- 1Potentiometer or a 1k Resistor$tw$);
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 2, $tw$Assemble components$tw$, $tw$Connect the Electronics$tw$, $tw$1. Power the breadboard (Connect the positive and negative ports on the breadboard to the 5V and GND on the Arduino)
2. Connect the LED lights on the breadboard (long leg is +/5V/Signal Pin, short leg is GND/- Connect the GND of the LED to a resistor and then to the blue line of the breadboard section that is powered. Each set of LEDs should all be on the same row for the GND. Connect the signal pin to ports on the Arduino.  Repeat the process for three sets of LEDs (Red, Yellow and Green)
3. Connect the signal pins to the Arduino ports
4. Compile the code and upload it to the Arduino.
5. Test the circuit
6. Build the artwork$tw$);
  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, 3, $tw$Assemble components$tw$, $tw$Upload the code$tw$, $tw$Copy this code into your Arduino IDE Application or go to Arduino.cc, create an account, login, open new project then copy the code editor and save the project as traffic\_lights

Cloud Arduino URL - app.arduino.cc

# //CODE

const int R1 = 1;

const int Y1= 2;

const int G1 = 3;

const int R2 = 5; 

const int Y2= 6;

const int G2 = 7;

const int R3 = 8; 

const int Y3= 9;

const int G3 = 10;

const int R4 = 11; 

const int Y4= 12;

const int G4 = 13;

void setup()

{

  

  pinMode(R1, OUTPUT);

  pinMode(G1, OUTPUT);

  pinMode(Y1, OUTPUT);

  pinMode(R2, OUTPUT);

  pinMode(Y2, OUTPUT);

  pinMode(G2, OUTPUT);

  pinMode(R3, OUTPUT);

  pinMode(G3, OUTPUT);

  pinMode(Y3, OUTPUT);

  pinMode(R4, OUTPUT);

  pinMode(Y4, OUTPUT);

  pinMode(G4, OUTPUT);

}

void loop()

{

  digitalWrite(R1, LOW);

  digitalWrite(Y1, LOW);

  digitalWrite(G1, HIGH);

  digitalWrite(R2, HIGH);

  digitalWrite(Y2, LOW);

  digitalWrite(G2, LOW);

  digitalWrite(R3, LOW);

  digitalWrite(Y3, LOW);

  digitalWrite(G3, HIGH);

  digitalWrite(R4, HIGH);

  digitalWrite(Y4, LOW);

  digitalWrite(G4, LOW);

  delay(8000);

  digitalWrite(R1, LOW);

  digitalWrite(Y1, HIGH);

  digitalWrite(G1, LOW);

  digitalWrite(R2, LOW);

  digitalWrite(Y2, HIGH);

  digitalWrite(G2, LOW);

  digitalWrite(R3, LOW);

  digitalWrite(Y3, HIGH);

  digitalWrite(G3, LOW);

  digitalWrite(R4, LOW);

  digitalWrite(Y4, HIGH);

  digitalWrite(G4, LOW);

  delay(3000);

  digitalWrite(R1,HIGH);

  digitalWrite(Y1, LOW);

  digitalWrite(G1, LOW);

  digitalWrite(R2, LOW);

  digitalWrite(Y2, LOW);

  digitalWrite(G2, HIGH);

  digitalWrite(R3, HIGH);

  digitalWrite(Y3, LOW);

  digitalWrite(G3, LOW);

  digitalWrite(R4, LOW);

  digitalWrite(Y4, LOW);

  digitalWrite(G4,HIGH);

  delay(8000);

  digitalWrite(R1, LOW);

  digitalWrite(Y1, HIGH);

  digitalWrite(G1, LOW);

  digitalWrite(R2, LOW);

  digitalWrite(Y2, HIGH);

  digitalWrite(G2, LOW);

  digitalWrite(R3, LOW);

  digitalWrite(Y3, HIGH);

  digitalWrite(G3, LOW);

  digitalWrite(R4, LOW);

  digitalWrite(Y4, HIGH);

  digitalWrite(G4, LOW);

  delay(3000);  

}$tw$);
end $$;
