#!/usr/bin/env python3
"""
Turn the Tutor LMS courses in a WordPress export into SQL for the new course
platform (supabase/lms.sql). One-off migration; no AI tokens, no network.

Run:  pip install markdownify
      python import_tutor.py content_source/wordpress/tinkerwith-export-20260819.xml

Writes supabase/private/seed-tutor-courses.sql (git-ignored: paid content). Paste it into Supabase → SQL Editor
→ Run, after lms.sql. Courses whose web address (slug) already exists are
skipped, so it is safe to run twice and never overwrites your edits.

What comes across: course titles, descriptions, cover pictures, topics (as
lesson sections) and lesson text. What doesn't: quiz questions — Tutor keeps
them in its own database tables, which aren't in a WordPress export — so the
script lists each quiz for re-entry in teach.html. Pictures keep their
tinkerwith.me/wp-content addresses; re-upload them in teach.html before
WordPress is switched off.
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

from markdownify import markdownify

NS = {
    "wp": "http://wordpress.org/export/1.2/",
    "content": "http://purl.org/rss/1.0/modules/content/",
}

# The real Tinkerwith courses (the others in the export are Tutor demo content).
COURSES = {
    4425: dict(slug="ai-skills-for-kids", title="AI Skills for Kids", age_range="7–9", position=1),
    4293: dict(slug="what-is-ai", title="What is Artificial Intelligence?", age_range="10+", position=2),
    4625: dict(slug="ai-beginners-workbook", title="AI Beginners Workbook", age_range="9–13", position=3),
    4649: dict(slug="robotics-101", title="Robotics 101", age_range="", position=4),
}
PAID_PRICE_KES = 1999   # Tutor's paid price was "10" (dollars?); change per course in teach.html.


def text(el, path):
    found = el.find(path, NS)
    return (found.text or "") if found is not None else ""


def to_markdown(html):
    html = re.sub(r"<!--.*?-->", "", html or "", flags=re.S)          # Gutenberg block comments
    html = re.sub(r'\s(style|class|id)="[^"]*"', "", html)
    md = markdownify(html, heading_style="ATX", bullets="-", strip=["span", "div", "figure"])
    md = re.sub(r"\*\*\s*\*\*", "", md)                                # empty bold runs
    md = re.sub(r"[ \t]+\n", "\n", md)
    md = re.sub(r"\n{3,}", "\n\n", md)
    return md.strip()


def plain(md, limit=180):
    s = re.sub(r"(?m)^\s*(?:[-*+]|\d+\.)\s+", "", md)                   # list markers
    s = re.sub(r"[#*_>`\[\]!]|\(http[^)]*\)", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s if len(s) <= limit else s[: limit - 1].rsplit(" ", 1)[0] + "…"


def sql_text(s):
    # Dollar-quote so lesson text never needs escaping.
    if not s:
        return "''"
    tag = "$tw$"
    assert tag not in s, "lesson text contains the quote marker"
    return f"{tag}{s}{tag}"


def main(export_path):
    root = ET.parse(export_path).getroot()
    items, kids = {}, {}
    for it in root.iter("item"):
        d = dict(
            id=int(text(it, "wp:post_id")), type=text(it, "wp:post_type"), status=text(it, "wp:status"),
            parent=int(text(it, "wp:post_parent") or 0), order=int(text(it, "wp:menu_order") or 0),
            title=(it.findtext("title") or "").strip(), body=text(it, "content:encoded"),
            url=text(it, "wp:attachment_url"),
            meta={m.findtext("wp:meta_key", namespaces=NS): (m.findtext("wp:meta_value", namespaces=NS) or "")
                  for m in it.findall("wp:postmeta", NS)},
        )
        items[d["id"]] = d
        kids.setdefault(d["parent"], []).append(d)
    order = lambda xs: sorted(xs, key=lambda x: (x["order"], x["id"]))

    out = ["-- Generated by import_tutor.py from the WordPress export. Run after lms.sql.",
           "-- Skips any course whose slug already exists, so your edits are never overwritten.", ""]
    report = []
    for cid, cfg in COURSES.items():
        c = items[cid]
        desc = to_markdown(c["body"])
        thumb = items.get(int(c["meta"].get("_thumbnail_id") or 0), {}).get("url", "")
        paid = c["meta"].get("_tutor_course_price_type") == "paid"
        lessons, quizzes, images = [], [], 0
        for topic in order(t for t in kids.get(cid, []) if t["type"] == "topics" and t["status"] == "publish"):
            for item in order(kids.get(topic["id"], [])):
                if item["status"] != "publish":
                    continue
                if item["type"] == "lesson":
                    body = to_markdown(item["body"])
                    images += body.count("](http")
                    lessons.append((topic["title"], item["title"], body))
                elif item["type"] == "tutor_quiz":
                    quizzes.append(f'{topic["title"]} → "{item["title"]}"' + (f' — {plain(to_markdown(item["body"]), 90)}' if item["body"].strip() else ""))
        report.append((cfg["title"], c["status"], paid, len(lessons), quizzes, images + desc.count("](http")))

        out.append(f"-- {cfg['title']}  (Tutor course {cid}, {c['status']})")
        out.append("do $$\ndeclare cid uuid;\nbegin")
        out.append(f"  if exists (select 1 from public.lms_courses where slug = '{cfg['slug']}') then return; end if;")
        out.append("  insert into public.lms_courses (slug, title, summary, description, age_range, cover_url, price_kes, is_published, position)")
        out.append(f"  values ('{cfg['slug']}', {sql_text(cfg['title'])}, {sql_text(plain(desc))}, {sql_text(desc)},")
        out.append(f"          {sql_text(cfg['age_range'])}, {sql_text(thumb)}, {PAID_PRICE_KES if paid else 0}, {'true' if c['status'] == 'publish' else 'false'}, {cfg['position']})")
        out.append("  returning id into cid;")
        for n, (section, title, body) in enumerate(lessons, 1):
            out.append(f"  insert into public.lms_lessons (course_id, position, section, title, body) values (cid, {n}, {sql_text(section)}, {sql_text(title)}, {sql_text(body)});")
        out.append("end $$;\n")

    dest = Path(__file__).resolve().parent / "supabase" / "private" / "seed-tutor-courses.sql"
    dest.parent.mkdir(exist_ok=True)
    dest.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {dest.relative_to(Path.cwd()) if dest.is_relative_to(Path.cwd()) else dest}\n")
    for title, status, paid, n, quizzes, imgs in report:
        print(f"{title}: {n} lessons, {'paid' if paid else 'free'}, {'published' if status == 'publish' else 'draft'}"
              + (f", {imgs} picture(s) still on WordPress" if imgs else ""))
        for q in quizzes:
            print(f"   quiz to re-enter: {q}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "content_source/wordpress/tinkerwith-export-20260819.xml")
